"""empty message

Revision ID: 322bfdf302cf
Revises: 
Create Date: 2023-12-26 07:34:43.130259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '322bfdf302cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('transmission', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Float(precision=2), nullable=False),
    sa.Column('release_year', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car_model')
    # ### end Alembic commands ###
